Add showdown option for sublists, #21
obedm503/bootmark pull request #23
Opened 2017-04-30 16:17 UTC by jolexa

Thanks for answering #21, I learned something.

This PR may help others in the future as well when looking at the kitchen sink example

2017-04-30 22:22 UTC, obedm503 approved these changes

2017-04-30 22:24 UTC, obedm503 requested changes
just change the base branch to development

2017-04-30 23:20 UTC, jolexa commented
changed to development branch

2017-05-01 05:37 UTC, obedm503 approved these changes

2017-05-01 05:37 UTC, merged